version: "3.6"

services:

  web:
    image: nginx:1.15
    volumes:
      - ./docroot:/docroot:ro
      - ./compose/nginx/gunicorn.template:/etc/nginx/conf.d/server_conf.template
    ports:
      - "8888:80"
    environment:
      NGINX_HOST: 127.0.0.1
      NGINX_PORT: 80
      NGINX_DOCUMENT_ROOT: /docroot
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$NGINX_DOCUMENT_ROOT' < /etc/nginx/conf.d/server_conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

